apiVersion: apps/v1
kind: Deployment
metadata:
  name: galindodeployment
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: galindoapp
  replicas: 1
  template:
    metadata:
      labels:
         app: galindoapp
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: galindo
           image: localhost:5000/galindo:latest
           ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: galindoservice
  namespace: thymeleaf
spec:
#  type: NodePort
  selector:
    app: galindodeployment
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080